# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VXsVP6FK5NM1cSYZRXhM9KMckg4FFV2O
"""



"""# New Section"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("/content/sample_data/netflix_titles.csv.zip")
df.head()

df.info()

df.isnull().sum()

df=df.dropna(subset=['director','country',])

df.head()

df=df.dropna(subset=['rating'])



# Drop rows where 'date_added' is missing
df.dropna(subset=['date_added'], inplace=True)

# Convert to datetime with error handling
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

# Drop rows where conversion failed (just in case)
df.dropna(subset=['date_added'], inplace=True)

# Fill other missing columns
df['director'] = df['director'].fillna("Unknown")
df['cast'] = df['cast'].fillna("Not specified")
df['country'] = df['country'].fillna("Unknown")
df['rating'] = df['rating'].fillna("Unknown")
df['duration'] = df['duration'].fillna("Unknown")

# Extract time features
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month
df['month_name_added'] = df['date_added'].dt.month_name()

plt.figure(figsize=(6,4))
df['type'].value_counts().plot(kind='bar', color=['skyblue', 'orange'])
plt.title("Content Type Distribution")
plt.ylabel("Count")
plt.xticks(rotation=0)
plt.show()

plt.figure(figsize=(10,5))
df['year_added'].value_counts().sort_index().plot(kind='bar', color='purple')
plt.title("Content Added per Year")
plt.xlabel("Year")
plt.ylabel("Count")
plt.show()

genres = df['listed_in'].str.split(', ').explode()
plt.figure(figsize=(10,5))
genres.value_counts().head(10).plot(kind='bar', color='green')
plt.title("Top 10 Genres on Netflix")
plt.ylabel("Number of Shows")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10,5))
df['month_name_added'].value_counts().reindex([
    'January','February','March','April','May','June',
    'July','August','September','October','November','December'
]).plot(kind='bar', color='slateblue')
plt.title("Month-wise Content Addition")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10,5))
df['director'].dropna().str.split(', ').explode().value_counts().head(10).plot(kind='bar', color='coral')
plt.title("Top 10 Directors on Netflix")
plt.ylabel("Number of Shows")
plt.xticks(rotation=45)
plt.show()

